### PR TITLE
Setup classes

### PR DESCRIPTION
**Pull request by brhanuhailu**
### In this pull request I:

- [X] Create class Person with the following:
   -  Instance vars: @id, @name, and @age.
   -  Create private method of_age? that returns true if @Age is greater or equal to 18 and false otherwise.
   -  Create public method can_use_services? that returns true if person is of age or if they have permission from parents.
- [X] Create class Student (subclass of person):
     -  Inherits from Person.
     -   Created Method play_hooky that returns "¯\(ツ)/¯".
- [X]  Create class Teacher witch:
     -   Inherited from Person.
     -   And Override can_use_services? so it always returns true.
- [X]  Each class has  saved in a separate file.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Brhanu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- The _Future Features_ section of your ReadMe should include 1-3 potential features to be added later. Let's bear in mind that our project can still be expanded with new features, even at the end of the milestone.
- Remove the Live demo link from the ReadMe if the app is not yet deployed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brhanuhailu** [comment]
Hello everyone please I submit the wrong submission button. this project is not for day one. I can't undo the submission. how can i undo and submit the today's project.

**Comment by brhanuhailu** [comment]
@rloterh  Thank you.

**Review by BregornOriginal — APPROVED** [review]
Hi @brhanuhailu 

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

giphy

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Excellent Pull Request description

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Pull request merged**
